openapi: 3.1.0
info:
  title: Scooter Rental API
  description: REST API for scooter rental system
  version: 1.0.0
  contact:
    name: Albert
    email: albertforeber2@gmail.com
servers:
  - url: 'http://localhost:8080/api'
    description: Local development

security:
  - bearerAuth: [ ]

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token

  examples:
    JsonParseException:
      summary: "Malformed JSON"
      description: "Appears when JSON is malformed"
      value:
        status: 400
        error: "Parse exception"
        message: "Failed to parse your request. Check all fields are correct"
        details:
          - "Request JSON body is malformed"

    MismatchedInputException:
      summary: "Invalid field or field is excessive"
      description: "Appears when wrong type given (e.g. array instead of single value) in JSON request or field is exessive"
      value:
        status: 400
        error: "Parse exception"
        message: "Failed to parse your request. Check all fields are correct"
        details:
          - "Invalid type for field or field is excessive: not_expected_field_name"

    InvalidFieldValue:
      summary: "Invalid field value"
      description: "Appears when field value is wrong (e.g. expected enum, but given value doesn't match any of expected values)"
      value:
        status: 400
        error: "Parse exception"
        message: "Failed to parse your request. Check all fields are correct"
        details:
          - "Invalid value for field: status"

    BodyValidationException:
      summary: "Body validation exception"
      description: "Appears when some of request body field failed to validate (e.g. field expected to be filled but sent null)"
      value:
        status: 400
        error: "Validation exception"
        message: "Some of fields failed to validate"
        details:
          - "name: Field 'name' should not be empty"

    SimpleValidationException:
      summary: "Param validation exception"
      description: "Appears when some of request body field failed to validate (e.g. field expected to be filled but sent null)"
      value:
        status: 400
        error: "Validation exception"
        message: "Some of path variables or params failed to validate"
        details:
          - "page: Param 'page' should be positive"

    NoSuchEntityException:
      summary: "No such entity"
      description: "Appears when user requested entity that doesn't exist"
      value:
        status: 400
        error: "No such entity exception"
        message: "Requested data was not found"
        details:
          - "No tariff found with id: 1"

    UnavailableActionException:
      summary: "Unavailable action"
      description: "Appears when user tries to perform unavailable action (e.g rent an occupied scooter)"
      value:
        status: 400
        error: "Unavailable action"
        message: "You are not able to perform such action"
        details:
          - "Forbidden to rent an occupied scooter"

    InvalidToken:
      summary: "Invalid token"
      description: "Appears provided invalid token (e.g expired)"
      value:
        status: 401
        error: "Invalid token"
        message: "Error during token validation"

    Unauthorized:
      summary: "No access token"
      description: "Appears when endpoints requires authorization but token was not provided"
      value:
        status: 401
        error: "Unauthorized"
        message: "No access token found"

    BadCredentials:
      summary: "Bad credentials"
      description: "Appears when logging in with wrong credentials"
      value:
        status: 401
        error: "Bad credentials"
        message: "Check password and username are correct"

    AccessDeniedException:
      summary: "Access denied"
      description: "Appears when user doesn't have enough permissions to user this endpoint"
      value:
        status: 403
        error: "Access denied"
        message: "You don't have required permissions"

    NoRequiredEntityException:
      summary: "No required entity"
      description: "Appears when request required some entity but server failed to find it (e.g. default tariff not found)"
      value:
        status: 500
        error: "No required entity exception"
        message: "Some of required data was not found. Please contact support team"

    DataManipulationException:
      summary: "Data manipulation exception"
      description: "Appears when server failed to process required data (e.g. database failed to perform some actions)"
      value:
        status: 500
        error: "Data manipulation exception"
        message: "Something went wrong during processing your request, please try later"

    Exception:
      summary: "Interval server error"
      description: "Appears when unexpected error occurred on server side"
      value:
        status: 500
        error: "Internal server error"
        message: "Something went wrong, please try again later"

  schemas:
# --------------- RESPONSES ---------------
    TokenResponse:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          description: "JWT access token для аутентификации запросов"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

        refreshToken:
          type: string
          description: "Токен для обновления истекшего access token"
          example: "8x4f9s2d-8b6g-4c3h-901a-2b3c4d5e6f7g"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        error:
          type: string
          example: Validation exception
        message:
          type: string
          example: Some of fields failed to validate
        details:
          type: array
          items:
            type: string
          example:
            - "Field 'email' must contain well-formed email address"

# --------------- REQUESTS ---------------
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 1
          pattern: '^S(.*\S)?$'
          example: "john_doe"
        password:
          type: string
          minLength: 1
          example: "securedSecret123"

    RefreshRequest:
      type: object
      required:
        - oldRefreshToken
      properties:
        oldRefreshToken:
          type: string
          minLength: 1
          description: "Текущий refresh токен, который необходимо обновить"
          example: "8x4f9s2d-8b6g-4c3h-901a-2b3c4d5e6f7g"

    RegisterRequest:
      type: object
      required:
        - username
        - password
        - dateOfBirth
        - email
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^\S(.*\S)?$'
          example: "john_doe"
        password:
          type: string
          minLength: 8
          example: "securePassword123"
        dateOfBirth:
          type: string
          format: date
          description: "Date of birth (must be in the past)"
          example: "2000-01-15"
        email:
          type: string
          format: email
          minLength: 6
          maxLength: 100
          example: "user@example.com"

    LogoutRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          minLength: 1
          description: "Refresh токен, который необходимо отозвать (деактивировать)"
          example: "8x4f9s2d-8b6g-4c3h-901a-2b3c4d5e6f7g"



paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: "Logging in"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'

      responses:
        '200':
          description: 'Logged in successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

        '400':
          description: "User side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                JsonParseException:
                  $ref: '#/components/examples/JsonParseException'
                MismatchedInputException:
                  $ref: '#/components/examples/MismatchedInputException'
                InvalidFieldValue:
                  $ref: '#/components/examples/InvalidFieldValue'
                BodyValidationException:
                  $ref: '#/components/examples/BodyValidationException'

        '500':
          description: "Server side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NoRequiredEntityException:
                  $ref: '#/components/examples/NoRequiredEntityException'
                DataManipulationException:
                  $ref: '#/components/examples/DataManipulationException'
                Exception:
                  $ref: '#/components/examples/Exception'

        '401':
          description: "Auth errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BadCredentials:
                  $ref: '#/components/examples/BadCredentials'

#        '401':
#          description: "Authorization errors"
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'
#              examples:
#                InvalidToken:
#                  $ref: '#/components/examples/InvalidToken'
#                Unauthorized:
#                  $ref: '#/components/examples/Unauthorized'
#
#        '403':
#          description: "Permission error"
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ErrorResponse'
#              examples:
#                AccessDeniedException:
#                  $ref: '#/components/examples/AccessDeniedException'

  /auth/register:
    post:
      tags: [Auth]
      summary: "Signing in"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'

      responses:
        '200':
          description: 'Registered successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

        '400':
          description: "User side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                JsonParseException:
                  $ref: '#/components/examples/JsonParseException'
                MismatchedInputException:
                  $ref: '#/components/examples/MismatchedInputException'
                InvalidFieldValue:
                  $ref: '#/components/examples/InvalidFieldValue'
                BodyValidationException:
                  $ref: '#/components/examples/BodyValidationException'

        '500':
          description: "Server side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NoRequiredEntityException:
                  $ref: '#/components/examples/NoRequiredEntityException'
                DataManipulationException:
                  $ref: '#/components/examples/DataManipulationException'
                Exception:
                  $ref: '#/components/examples/Exception'

  /auth/refresh:
    post:
      tags: [ Auth ]
      summary: "Refreshing token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'

      responses:
        '200':
          description: 'Refreshed successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

        '400':
          description: "User side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                JsonParseException:
                  $ref: '#/components/examples/JsonParseException'
                MismatchedInputException:
                  $ref: '#/components/examples/MismatchedInputException'
                InvalidFieldValue:
                  $ref: '#/components/examples/InvalidFieldValue'
                BodyValidationException:
                  $ref: '#/components/examples/BodyValidationException'
                NoSuchEntityException:
                  $ref: '#/components/examples/NoSuchEntityException'

        '500':
          description: "Server side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NoRequiredEntityException:
                  $ref: '#/components/examples/NoRequiredEntityException'
                DataManipulationException:
                  $ref: '#/components/examples/DataManipulationException'
                Exception:
                  $ref: '#/components/examples/Exception'

  /auth/logout:
    post:
      tags: [ Auth ]
      summary: "Logging out"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'

      responses:
        '204':
          description: 'Logged out successfully'

        '400':
          description: "User side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                JsonParseException:
                  $ref: '#/components/examples/JsonParseException'
                MismatchedInputException:
                  $ref: '#/components/examples/MismatchedInputException'
                InvalidFieldValue:
                  $ref: '#/components/examples/InvalidFieldValue'
                BodyValidationException:
                  $ref: '#/components/examples/BodyValidationException'
                NoSuchEntityException:
                  $ref: '#/components/examples/NoSuchEntityException'

        '500':
          description: "Server side errors"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NoRequiredEntityException:
                  $ref: '#/components/examples/NoRequiredEntityException'
                DataManipulationException:
                  $ref: '#/components/examples/DataManipulationException'
                Exception:
                  $ref: '#/components/examples/Exception'